<?php
// PLUGIN: Advanced Custom Fields (ACF)

// FOR DEALS
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_offer-details',
		'title' => 'Offer details',
		'fields' => array (
			array (
				'key' => 'field_5a3cd12b989de',
				'label' => 'Reference code',
				'name' => 'deal-ref',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a3ba4ae56dea',
				'label' => 'Contract',
				'name' => 'deal-contract',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					1 => '1 month',
					6 => '6 months',
					12 => '12 months',
					18 => '18 months',
					24 => '24 months',
				),
				'default_value' => 12,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5a3ba3a756de7',
				'label' => 'Price',
				'name' => 'deal-price',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '£',
				'append' => 'per month',
				'min' => 0,
				'max' => '',
				'step' => '0.01',
			),
			array (
				'key' => 'field_5a3ba3f056de8',
				'label' => 'and the Price is valid for',
				'name' => 'deal-price-for',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					1 => '1 month',
					6 => '6 months',
					12 => '12 months',
					18 => '18 months',
					24 => '24 months',
				),
				'default_value' => 12,
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5a3ba59f56deb',
				'label' => 'Price after that',
				'name' => 'deal-price-after',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '0.00',
				'prepend' => '£',
				'append' => 'per month',
				'min' => 0,
				'max' => '',
				'step' => '0.01',
			),
			array (
				'key' => 'field_5a3bb8ef235bf',
				'label' => 'Line rent',
				'name' => 'deal-line-rent',
				'type' => 'number',
				'required' => 1,
				'default_value' => '0.00',
				'placeholder' => '0.00',
				'prepend' => '£',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => '0.01',
			),
			array (
				'key' => 'field_5a3ba45e56de9',
				'label' => 'Setup costs',
				'name' => 'deal-setup-costs',
				'type' => 'number',
				'required' => 1,
				'default_value' => '0.00',
				'placeholder' => '0.00',
				'prepend' => '£',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => '0.01',
			),
			array (
				'key' => 'field_5a3bb0a6b1c97',
				'label' => 'Total first year cost',
				'name' => 'deal-total-first-year',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'First year cost',
				'prepend' => '£',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => '0.01',
			),
			array (
				'key' => 'field_5a3bb11eb1c98',
				'label' => 'Total overall contract cost',
				'name' => 'deal-total-contract',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Overall cost over contract term',
				'prepend' => '£',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => '0.01',
			),
			array (
				'key' => 'field_5a3ba819f83c1',
				'label' => 'Deal valid from',
				'name' => 'deal-from',
				'type' => 'date_picker',
				'instructions' => 'This is used just for display and filter only. Please use the <b>Publish</b> box at the top of the sidebar to schedule the deal on the site.',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5a3ba850f83c2',
				'label' => 'To',
				'name' => 'deal-to',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_5a3bb03dc60ad',
				'label' => 'Incentive',
				'name' => 'deal-incentive',
				'type' => 'wysiwyg',
				'instructions' => 'Cashback, vouchers, ...',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5a3bb2fff7201',
				'label' => 'Eligibility - Who is entitled',
				'name' => 'deal-eligibility',
				'type' => 'select',
				'choices' => array (
					'Anyone' => 'Anyone',
					'New customers only' => 'New customers only',
					'Upgrading only' => 'Upgrading only',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5a3bb3b37df41',
				'label' => 'Dependencies',
				'name' => 'deal-dependencies',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'deal',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_broadband-details',
		'title' => 'Broadband details',
		'fields' => array (
			array (
				'key' => 'field_5a3bb465553bb',
				'label' => 'Broadband type',
				'name' => 'bb-type',
				'type' => 'select',
				'choices' => array (
					'N/A' => 'Not Available',
					'Broadband' => 'Broadband',
					'Fibre' => 'Fibre',
				),
				'default_value' => 'N/A',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5a3baa8ec2bd8',
				'label' => 'Monthly usage allowance',
				'name' => 'bb-usage',
				'type' => 'select',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5a3bb465553bb',
							'operator' => '!=',
							'value' => 'N/A',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'Unlimited' => 'Unlimited',
					'Unlimited - Fair Usage' => 'Unlimited - Fair Usage',
					'Limited' => 'Limited',
				),
				'default_value' => 'Unlimited',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5a3ba6e6126bf',
				'label' => 'Download',
				'name' => 'bb-download',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5a3bb465553bb',
							'operator' => '!=',
							'value' => 'N/A',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 17,
				'placeholder' => 'please type a number',
				'prepend' => 'Up to',
				'append' => 'Mb',
				'min' => 0,
				'max' => '',
				'step' => 1,
			),
			array (
				'key' => 'field_5a3ba741126c0',
				'label' => 'Upload',
				'name' => 'bb-upload',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5a3bb465553bb',
							'operator' => '!=',
							'value' => 'N/A',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 1,
				'placeholder' => 'please type a number',
				'prepend' => 'Up to',
				'append' => 'Mb',
				'min' => 0,
				'max' => '',
				'step' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'deal',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 2,
	));
}
